### ISSUE TITLE
SinaWeiboFansRemover的Tampermonkey 版本

### ISSUE THREAD

**Issue by RingoTC** [GeeLaw/SinaWeiboFansRemover#1]
因为Edge扩展安装较麻烦，所以我转制了一份**[Tampermonkey](https://tampermonkey.net/)**版本。
通过Tampermonkey，可以在Chrome、Edge、Firefox等各种主流浏览器上使用这份脚本。
在线安装地址：[SinaWeiboFansRemover](https://greasyfork.org/zh-CN/scripts/371340-sinaweibofansremover)

**Comment by GeeLaw** [comment]
谢谢。

我还没有测试代码是否能在其他浏览器上跑通。在 Edge 的 Tampermonkey 上安装之后会显示一个错误页面，但是安装仍然是成功了的。使用 Tampermonkey 可以免去 sideloading 的麻烦。

**Comment by GeeLaw** [comment]
似乎这个版本在域名是 `www.weibo.com` 的时候不起作用——在一些电脑/网络上，微博的域名是 `www.weibo.com` 而不是 apex `weibo.com`。

**Comment by RingoTC** [comment]
已更新匹配 www.weibo.com。
